tabs:
    last_close: startpage
    mousewheel_switching: false
    new_position:
        related: next
        unrelated: next
    position: left
    select_on_remove: next
    show: always
    title:
        format_pinned: "[{index}]: {title}"

url:
    start_pages: https://www.google.com

editor:
    command: ['urxvt', '-name', 'qute-editor', '-e', 'zsh', '-c',
              'vim --noplugin -N -u ~/.config/qutebrowser/editor.vimrc {}']

content:
    geolocation: true

downloads:
    remove_finished: 10000
