# ~/.config/tmuxinator/<%= name %>.yml

root: <%%= @settings['root'] %>
name: <%= name %>

on_project_stop:

windows:
    - A:
        layout: main-vertical
        panes:
            - 0:
                - lls
    - B:
        layout: main-vertical
        panes:
            - 0:
                - lls
    - C:
        layout: main-vertical
        panes:
            - 0:
                - lls
