# ~/.config/tmuxinator/<%= name %>.yml

root: <%%= @settings['root'] %>
name: <%= name %>

on_project_stop:

windows:
    - I:
        layout: even-horizontal
        panes:
            - 0:
                - ll
    - II:
        layout: even-horizontal
        panes:
            - 0:
                - ll
    - III:
        layout: even-horizontal
        panes:
            - 0:
                - ll
