# ~/.config/tmuxinator/<%= name %>.yml

root: <%%= @settings['root'] %>
name: <%= name %>

on_project_stop:

windows:
    - I:
        layout: main-vertical
        panes:
            - master:
                - clear
    - II:
        layout: main-vertical
    - III:
        layout: main-vertical
