# ~/.config/tmuxinator/<%= name %>.yml

root: <%%= @settings['root'] %>
name: <%= name %>

on_project_stop:

windows:
    - src:  #A:
        layout: even-horizontal
        panes:
            - 0:
                - lls
    - tests:  #B:
        layout: even-horizontal
        panes:
            - 0:
                - lls
    - debug:  #C:
        layout: even-horizontal
        panes:
            - 0:
                - lls
    - docs:  #D:
        layout: even-horizontal
        panes:
            - 0:
                - lls
    - configs:  #E:
        layout: even-horizontal
        panes:
            - 0:
                - lls
