# ~/.config/tmuxinator/<%= name %>.yml

root: <%%= @settings['root'] %>
name: <%= name %>

pre_window: tmux setenv TMUXINATOR_ROOT_${TMUX_PANE##%} $(pwd)
on_project_stop:

windows:
    - I:
        layout: even-horizontal
        panes:
            - 0:
                - ll
    - II:
        layout: even-horizontal
        panes:
            - 0:
                - ll
    - III:
        layout: even-horizontal
        panes:
            - 0:
                - ll
