# ~/.config/tmuxinator/<%= name %>.yml

root: <%%= @settings['root'] %>
name: <%= name %>

on_project_stop:

windows:
    - A:
        layout: main-vertical
        panes:
            - 0:
                - if [ $(pwd) != /home/bryan ]; then; tree; else; clear && ls -a && echo; fi
    - B:
        layout: main-vertical
        panes:
            - 0:
    - C:
        layout: main-vertical
        panes:
            - 0:
