# ~/.config/tmuxinator/<%= name %>.yml

root: <%%= @settings['root'] %>
name: <%= name %>

on_project_stop:

windows:
    - src:
        layout: even-horizontal
        panes:
            - 0:
                - lls
    - tests:
        layout: even-horizontal
        panes:
            - 0:
                - lls
    - debug:
        layout: even-horizontal
        panes:
            - 0:
                - lls
    - docs:
        layout: even-horizontal
        panes:
            - 0:
                - lls
    - configs:
        layout: even-horizontal
        panes:
            - 0:
                - lls
