# ~/.config/tmuxinator/<%= name %>.yml

root: <%%= @settings['root'] %>
name: <%= name %>

on_project_stop:

windows:
    - I:
        layout: main-vertical
        panes:
            - 0:
                - if [ $(pwd) != /home/bryan ]; then; tree; else; clear; fi
    - II:
        layout: main-vertical
        panes:
    - III:
        layout: main-vertical
        panes:
