tabs:
    position: left
    mousewheel_switching: false
    show: always
    last_close: close
    select_on_remove: next
    new_position:
        related: next
        unrelated: next

url:
    start_pages: https://www.google.com

editor:
    command: ['urxvt', '-name', 'qute-editor', '-e', 'zsh', '-c',
              'vim -S ~/.config/qutebrowser/editor.vimrc {}']

content:
    geolocation: true

downloads:
    remove_finished: 10000
