completion:
    web_history:
        max_items: -1

content:
    geolocation: true
    host_blocking:
        enabled: false
        whitelist: ['analytics.google.com']

downloads:
    remove_finished: 10000

editor:
    command: ['urxvt', '-name', 'qute-editor', '-e', 'zsh', '-c',
              'vim --noplugin -N -u ~/.config/qutebrowser/editor.vimrc {}']

tabs:
    last_close: startpage
    max_width: 250
    mousewheel_switching: false
    new_position:
        related: next
        unrelated: next
    position: top
    select_on_remove: next
    show: always
    title:
        format_pinned: "[{index}]"

url:
    start_pages: https://www.google.com

window:
    title_format: qutebrowser
